import { weapons, models, core, armyRule, ability, superHeavyWalker, datasheet, kwb } from './build-phase2-datasheets.mjs'

export const datasheets = [

datasheet({
  name: 'Ghazghkull Thraka', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Adamantine 'Eadbutt; Gork's Klaw; Mork's Roar.`,
  models: models(`Ghazghkull Thraka|8"|10|2+|4+|16|6+|4|`),
  weapons: weapons(
    `Mork's Roar - Aimed [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 4]|36"|12|5+|6|-1|1`,
    `Mork's Roar - Point Blank [CLOSE-QUARTERS, TORRENT]|9"|2D6+2|-|6|-1|1`,
    `Adamantine 'Eadbutt [DEVASTATING WOUNDS, EXTRA ATTACKS, PRECISION]|Melee|1|2+|14|-2|D3+3`,
    `Gork's Klaw [CLEAVE 2, DEVASTATING WOUNDS]|Melee|7|2+|14|-3|4`,
  ),
  abilities: [
    armyRule('Da Boss'), armyRule('Waaagh!'),
    ability("Da Grand Warlord's Ladz", `While this unit is within 3" of another friendly ${kwb('ORKS INFANTRY')} unit, this unit has Lone Operative.`),
    ability("Makari, Hoist Dat Banner!", `(Once per battle, per army): In your Movement phase, you can select a number of friendly ${kwb('ORKS')} units equal to or less than the current battle round number. Those units are riled up until the start of your next turn.`),
    ability('Prophet of da Great Waaagh!', `(Aura): While a friendly ${kwb('ORKS')} unit is within 6" of this unit, that unit's melee attacks have +1 to hit rolls and +1 to wound rolls.`, { effects: { hitMod: 1, woundMod: 1 }, combatType: 'melee', appliesToNearby: true }),
    ability('Supreme Commander', `If this model is in your army, it must be your ${kwb('WARLORD')}.`),
  ],
  keywords: ['Infantry', 'Character', 'Epic Hero', 'Explosives', 'Warboss'],
  unitComposition: ['1 Ghazghkull Thraka'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: "adamantine 'eadbutt", count: 1 }, { name: "gork's klaw", count: 1 }, { name: "mork's roar", count: 1 }],
}),

datasheet({
  name: 'Nazdreg', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Kustom Blasta X; Moonchewa.`,
  models: models(`Nazdreg|5"|7|2+|5+|8|6+|1|`),
  weapons: weapons(
    `Kustom Blasta X - Gatler [HAZARDOUS]|24"|6|4+|9|-2|3`,
    `Kustom Blasta X - Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|18"|4|4+|5|-1|1`,
    `Kustom Blasta X - Skorcha [BLAST 1, TORRENT]|12"|3|-|5|-1|1`,
    `Kustom Blasta X [CLEAVE 1, EXTRA ATTACKS]|Melee|6|2+|5|-1|1`,
    `Moonchewa [CLEAVE 1, TWIN-LINKED]|Melee|5|2+|12|-2|3`,
  ),
  abilities: [
    core('Deep Strike'), core('Leader'), armyRule('Da Boss'), armyRule('Waaagh!'),
    ability('Intimidating Motivation', `(Once per battle round, per army): In your Movement phase, at the start or end of this unit's move, you can select one friendly ${kwb('ORKS')} unit within 6" of this unit. That unit is no longer battle-shocked and is riled up until the start of your next turn.`),
    ability("Nazdreg's Know-wotz", `This unit has Deep Strike. This unit's ranged attacks have ${kwb('[IGNORES COVER]')}.`),
    ability("Supreme Kunnin'", `(Once per phase, per army): In your opponent's Movement phase, when an enemy unit ends a move within 8" of this unit, if this unit is unengaged, this unit can make a normal move of up to D6", or of up to 5" if this unit is riled up.`),
  ],
  keywords: ['Infantry', 'Character', 'Epic Hero', 'Mega Armour', 'Warboss'],
  unitComposition: ['1 Nazdreg'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'kustom blasta x', count: 1 }, { name: 'moonchewa', count: 1 }],
}),

datasheet({
  name: 'Warboss', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Kustom Choppa; Kustom Shoota.`,
  models: models(`Warboss|6"|6|4+|5+|6|6+|1|40mm`),
  weapons: weapons(
    `Kombi-rokkit - Busta Rokkit|24"|1|5+|10|-2|3`,
    `Kombi-rokkit - Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 1]|18"|2|5+|4|0|1`,
    `Kombi-skorcha - Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 1]|18"|2|5+|4|0|1`,
    `Kombi-skorcha - Skorcha [BLAST 1, TORRENT]|12"|3|-|5|0|1`,
    `Kustom Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|18"|4|5+|4|0|1`,
    `Kustom Choppa [CLEAVE 2]|Melee|6|2+|7|-2|2`,
    `Power Klaw|Melee|6|2+|12|-2|2`,
  ),
  options: [
    { button: '•', description: "This model's Kustom Choppa can be replaced with 1 Power Klaw." },
    { button: '•', description: "This model's Kustom Shoota can be replaced with one of the following: 1 Kombi-rokkit; 1 Kombi-skorcha." },
  ],
  abilities: [
    core('Leader'), armyRule('Da Boss'), armyRule('Waaagh!'),
    ability("Boss' Ammo Runt", `(Once per battle, per unit): In your Shooting phase, when this unit is selected to shoot, you can use this ability. If you do, this model's ranged attacks have +1 to hit rolls.`, { effects: { hitMod: 1 }, combatType: 'ranged', bearerOnly: true }),
    ability('Might Is Right', `If this unit made a charge move this turn, this model's melee attacks have +3 A and +2 S.`, { effects: { attacksMod: 3, strengthMod: 2 }, combatType: 'melee', bearerOnly: true }),
    ability('Intimidating Motivation', `(Once per battle round, per army): In your Movement phase, at the start or end of this unit's move, you can select one friendly ${kwb('ORKS')} unit within 6" of this unit. That unit is no longer battle-shocked and is riled up until the start of your next turn.`),
  ],
  keywords: ['Infantry', 'Character', 'Explosives', 'Warboss'],
  unitComposition: ['1 Warboss'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'kustom choppa', count: 1 }, { name: 'kustom shoota', count: 1 }],
}),

datasheet({
  name: 'Warboss in Mega Armour', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Big Shoota; 'Uge Choppa.`,
  models: models(`Warboss in Mega Armour|5"|7|2+|5+|7|6+|1|`),
  weapons: weapons(
    `Big Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|36"|3|4+|5|0|1`,
    `'Uge Choppa [CLEAVE 2]|Melee|5|2+|12|-2|3`,
  ),
  abilities: [
    core('Leader'), armyRule('Da Boss'), armyRule('Waaagh!'),
    ability("Krushin' Impetus", `When this unit ends a charge move, select one enemy unit engaged with this unit and roll one D6 for each model engaged with that enemy unit: for each 3+, that enemy unit suffers 1 mortal wound.`),
    ability('Intimidating Motivation', `(Once per battle round, per army): In your Movement phase, at the start or end of this unit's move, you can select one friendly ${kwb('ORKS')} unit within 6" of this unit. That unit is no longer battle-shocked and is riled up until the start of your next turn.`),
  ],
  keywords: ['Infantry', 'Character', 'Mega Armour', 'Warboss'],
  unitComposition: ['1 Warboss in Mega Armour'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'big shoota', count: 1 }, { name: "'uge choppa", count: 1 }],
}),

datasheet({
  name: 'Big Mek', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Kustom Mega-blasta; Power Klaw.`,
  models: models(`Big Mek|6"|5|3+||6|7+|1|`),
  weapons: weapons(
    `Kustom Mega-blasta [HAZARDOUS]|24"|3|4+|9|-2|3`,
    `Traktor Blasta [ANTI-FLY 2+]|24"|3|4+|6|-2|D3+3`,
    `Drilla|Melee|3|3+|12|-3|3`,
    `Power Klaw|Melee|5|3+|10|-2|2`,
  ),
  options: [
    { button: '•', description: "This model's Power Klaw can be replaced with 1 Drilla." },
    { button: '•', description: "This model's Kustom Mega-blasta can be replaced with 1 Traktor Blasta." },
  ],
  abilities: [
    core('Leader'), armyRule('Waaagh!'),
    ability('More Dakka', `This model's ranged attacks have ${kwb('[IGNORES COVER]')}. While this unit is riled up, this model's ranged attacks also have ${kwb('[SUSTAINED HITS 1]')}.`, { effects: {}, combatType: 'ranged' }),
    ability('Shokk-boosta', `In your Movement phase, when this unit is selected to advance, this unit can change its advance roll to a 6 and can move through all types of model. When this unit ends that advance move, make a hazard roll for each model in this unit.`),
  ],
  keywords: ['Infantry', 'Character', 'Explosives'],
  unitComposition: ['1 Big Mek'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'kustom mega-blasta', count: 1 }, { name: 'power klaw', count: 1 }],
}),

datasheet({
  name: 'Big Mek in Mega Armour', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Kustom Shoota; Power Klaw.`,
  models: models(`Big Mek in Mega Armour|6"|6|2+||6|7+|1|`),
  weapons: weapons(
    `Kombi-weapon - Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 1]|18"|2|4+|4|0|1`,
    `Kombi-weapon - Kill Shot|24"|1|4+|10|-2|3`,
    `Kombi-weapon - Point Blank [BLAST 1, TORRENT]|12"|3|-|5|0|1`,
    `Kustom Mega-blasta [HAZARDOUS]|24"|3|4+|9|-2|3`,
    `Kustom Shoota - Aimed [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|18"|4|4+|4|0|1`,
    `Kustom Shoota - Point Blank [CLOSE-QUARTERS, TORRENT]|6"|D3+3|-|4|0|1`,
    `Tellyport Blasta [BLAST 1]|12"|6|4+|9|-2|3`,
    `Killsaw|Melee|3|4+|10|-2|3`,
    `Power Klaw|Melee|3|3+|10|-2|2`,
  ),
  options: [
    { button: '•', description: 'This model can be equipped with one of the following: 1 Tellyport Blasta; 1 Kustom Force Field.' },
    { button: '•', description: "This model's Kustom Shoota can be replaced with one of the following: 1 Killsaw; 1 Kombi-weapon; 1 Kustom Mega-blasta." },
  ],
  abilities: [
    core('Leader'), armyRule('Waaagh!'),
    ability('Fix Dat Armour Up', `(Once per battle, per unit): In your Command phase, you can use this ability. If you do, this unit heals 3 wounds.`),
    ability('More Dakka', `This model's ranged attacks have ${kwb('[IGNORES COVER]')}. While this unit is riled up, this model's ranged attacks also have ${kwb('[SUSTAINED HITS 1]')}.`, { effects: {}, combatType: 'ranged' }),
    ability('Kustom Force Field', `(Wargear ability): This unit has a 4+ invulnerable save against ranged attacks.`, { effects: { saveMod: 1 }, combatType: 'ranged', target: 'defender' }),
  ],
  keywords: ['Infantry', 'Big Mek', 'Character', 'Explosives', 'Mega Armour'],
  unitComposition: ['1 Big Mek in Mega Armour'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'kustom shoota', count: 1 }, { name: 'power klaw', count: 1 }],
}),

datasheet({
  name: 'Big Mek with Shokk Attack Gun', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Big Mek's Toolz; Shokk Attack Gun.`,
  models: models(`Big Mek with Shokk Attack Gun|6"|5|4+||5|7+|1|`),
  weapons: weapons(
    `Shokk Attack Gun [BLAST 1, HEAVY]|60"|D3+3|5+|12|-4|D6+1`,
    `Big Mek's Toolz|Melee|4|3+|5|0|1`,
  ),
  abilities: [
    core('Leader'), armyRule('Waaagh!'),
    ability('More Dakka', `This model's ranged attacks have ${kwb('[IGNORES COVER]')}. While this unit is riled up, this model's ranged attacks also have ${kwb('[SUSTAINED HITS 1]')}.`, { effects: {}, combatType: 'ranged' }),
    ability('Support Shokka', `While this model is within 3" of a friendly ${kwb('ORKS INFANTRY')} unit (excluding ${kwb('BIG MEK WITH SHOKK ATTACK GUN')} units), this model has Lone Operative.`),
  ],
  keywords: ['Infantry', 'Big Mek', 'Character', 'Explosives'],
  unitComposition: ["1 Big Mek with Shokk Attack Gun"], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: "big mek's toolz", count: 1 }, { name: 'shokk attack gun', count: 1 }],
}),

datasheet({
  name: 'Big Mek Dakkarig', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Blitzkannon; Multi-busta Launcha; Stompy Feet.`,
  models: models(`Big Mek Dakkarig|8"|8|3+|5+|11|7+|3|`),
  weapons: weapons(
    `Blitzkannon [IGNORES COVER, LETHAL HITS: non-MONSTER/VEHICLE]|24"|8|4+|7|-2|2`,
    `Multi-busta Launcha [IGNORES COVER, LETHAL HITS]|24"|6|5+|10|-2|3`,
    `Stompy Feet|Melee|4|3+|6|-1|1`,
  ),
  abilities: [
    core('Deadly Demise 1'), armyRule('Waaagh!'),
    ability('Even More Dakka', `While this unit is riled up, this unit's ranged attacks have ${kwb('[SUSTAINED HITS 1]')}.`, { effects: { sustainedHitsBonus: 1 }, combatType: 'ranged' }),
    ability('Blitz Dem Gitz!', `In your Shooting phase, if this model's Blitzkannon targets a unit (excluding ${kwb('MONSTER')} and ${kwb('VEHICLE')} units), that weapon has +6 A.`),
  ],
  keywords: ['Vehicle', 'Big Mek', 'Character', 'Walker'],
  unitComposition: ['1 Big Mek Dakkarig'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'blitzkannon', count: 1 }, { name: 'multi-busta launcha', count: 1 }, { name: 'stompy feet', count: 1 }],
}),

datasheet({
  name: 'Mek', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Kustom Mega-slugga; Mek's Toolz.`,
  models: models(`Mek|6"|5|5+||4|7+|1|`),
  weapons: weapons(
    `Kustom Mega-slugga [CLOSE-QUARTERS, HAZARDOUS]|12"|3|4+|8|-2|3`,
    `Mek's Toolz|Melee|3|3+|5|0|1`,
  ),
  abilities: [
    core('Support'), armyRule('Waaagh!'),
    ability('Kustom Dakka', `This model's ranged attacks have ${kwb('[IGNORES COVER]')}.`, { effects: {}, combatType: 'ranged' }),
    ability("Clever Know-wotz", `In your Movement phase, at the start or end of this unit's move, you can select one friendly ${kwb('ORKS VEHICLE')} model (excluding ${kwb('AIRCRAFT')} and ${kwb('TITANIC')} models) within 3" of this unit. That model heals D3 wounds and that model's attacks have +1 to hit rolls until the start of your next Movement phase.`),
  ],
  keywords: ['Infantry', 'Character', 'Explosives'],
  unitComposition: ['1 Mek'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'kustom mega-slugga', count: 1 }, { name: "mek's toolz", count: 1 }],
}),

datasheet({
  name: 'Deffkilla Wartrike', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Boomstikks; Killa Jet; Snagga Klaw.`,
  models: models(`Deffkilla Wartrike|12"|6|4+|5+|9|6+|3|`),
  weapons: weapons(
    `Boomstikks [ASSAULT, LETHAL HITS: non-MONSTER/VEHICLE]|12"|6|5+|5|0|1`,
    `Snagga Klaw [ASSAULT, PRECISION]|12"|1|5+|7|-2|2`,
    `Killa Jet - Burna [CLEAVE 1, EXTRA ATTACKS]|Melee|3|3+|5|-1|1`,
    `Killa Jet - Cutta [EXTRA ATTACKS]|Melee|1|3+|10|-3|D6+2`,
    `Snagga Klaw [CLEAVE 2]|Melee|5|2+|7|-2|2`,
  ),
  abilities: [
    core('Deadly Demise 1'), core('Leader'), armyRule('Da Boss'), armyRule('Waaagh!'),
    ability('Get Back in da Race!', `(Once per battle round, per army): In your Movement phase, at the start or end of this unit's move, you can select one friendly ${kwb('SPEED FREEKS')} unit within 6" of this unit (and any units embarked within it). That unit is no longer battle-shocked and is riled up until the start of your next turn.`),
    ability('Fuel-mixa Grot', `This unit has +1 to advance rolls.`),
  ],
  keywords: ['Mounted', 'Character', 'Speed Freeks', 'Warboss'],
  unitComposition: ['1 Deffkilla Wartrike'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'boomstikks', count: 1 }, { name: 'killa jet', count: 1 }, { name: 'snagga klaw', count: 1 }],
}),

datasheet({
  name: 'Beastboss', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Shoota; Beast Snagga Klaw and Beastchoppa.`,
  models: models(`Beastboss|6"|6|4+|5+|6|6+|1|`),
  weapons: weapons(
    `Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 1]|18"|2|4+|4|0|1`,
    `Beast Snagga Klaw and Beastchoppa [SUSTAINED HITS 2: MONSTER/VEHICLE]|Melee|6|2+|12|-2|2`,
  ),
  abilities: [
    core('Feel No Pain 6+'), core('Leader'), armyRule('Da Boss'), armyRule('Waaagh!'),
    ability("Keep Huntin'!", `(Once per battle round, per army): In your Movement phase, at the start or end of this unit's move, you can select one friendly ${kwb('BEAST SNAGGA')} unit within 6" of this unit. That unit is no longer battle-shocked and is riled up until the start of your next turn.`),
    ability('Dodge Dis!', `This model's attacks have +1 to hit rolls.`),
  ],
  keywords: ['Infantry', 'Beast Snagga', 'Character', 'Warboss'],
  unitComposition: ['1 Beastboss'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'shoota', count: 1 }, { name: 'beast snagga klaw and beastchoppa', count: 1 }],
}),

datasheet({
  name: 'Zodgrod Wortsnagga', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Da Grabzappa; Squigstoppa.`,
  models: models(`Zodgrod Wortsnagga|6"|5|5+|6+|5|7+|1|`),
  weapons: weapons(
    `Squigstoppa [ANTI-MONSTER/VEHICLE 4+, CLOSE-QUARTERS, DEVASTATING WOUNDS: MONSTER/VEHICLE]|12"|1|5+|4|-1|1`,
    `Da Grabzappa|Melee|5|2+|7|-2|2`,
  ),
  abilities: [
    core('Leader'), armyRule('Waaagh!'),
    ability('Super Runts', `This unit is riled up. Friendly ${kwb('GRETCHIN')} units' Scavenged Shivs weapons have +1 A, +1 to WS rolls and +1 S while this model is leading them.`),
  ],
  keywords: ['Infantry', 'Character', 'Epic Hero', 'Runtherd'],
  unitComposition: ['1 Zodgrod Wortsnagga'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'da grabzappa', count: 1 }, { name: 'squigstoppa', count: 1 }],
}),

datasheet({
  name: 'Wazdakka Gutsmek', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Speeding Bulk and Flaming Exhaust; Fixit's Wrench; Grabba Dragga; Psyko-gatler.`,
  models: models(`Wazdakka Gutsmek|14"|8|3+|4+|10|6+|3|`),
  weapons: weapons(
    `Grabba Dragga [ASSAULT, PRECISION]|12"|1|2+|10|-2|3`,
    `Psyko-gatler [ASSAULT, LETHAL HITS: non-MONSTER/VEHICLE, SUSTAINED HITS 1]|24"|12|4+|6|-2|2`,
    `Speeding Bulk and Flaming Exhaust [CLEAVE 1, EXTRA ATTACKS]|Melee|3|2+|5|-1|1`,
    `Fixit's Wrench [EXTRA ATTACKS]|Melee|1|4+|3|0|1`,
    `Grabba Dragga [CLEAVE 2, LANCE]|Melee|6|2+|10|-2|3`,
  ),
  abilities: [
    core('Deadly Demise D3'), core('Deep Strike'), core('Lone Operative'), armyRule('Waaagh!'),
    ability('Full Throttle', `(Once per battle round, in your Command phase): select one of this unit's Throttlerokkit Shokka Engine abilities below. This unit has that ability until the start of your next Command phase.<br><br><b>Turbo Engine:</b> When this unit is selected to make an advance or fall-back move, that move does not prevent this unit from being eligible to declare a charge.<br><br><b>Shokk Attack Engine:</b> In your Command phase, if this unit is unengaged, you can place this unit into strategic reserves.<br><br><b>Pulse Jet:</b> In your Movement phase, when this unit is selected to move, if this unit is unengaged, this unit can make a pulse jet move.`),
  ],
  keywords: ['Mounted', 'Vehicle', 'Character', 'Epic Hero', 'Smoke', 'Speed Freeks'],
  unitComposition: ['1 Wazdakka Gutsmek'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'speeding bulk and flaming exhaust', count: 1 }, { name: "fixit's wrench", count: 1 }, { name: 'grabba dragga', count: 1 }, { name: 'psyko-gatler', count: 1 }],
}),

datasheet({
  name: 'Mozrog Skragbad', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Big Chompa's Jaws; Gutrippa; Thump Gun.`,
  models: models(`Mozrog Skragbad|10"|9|3+|4+|10|6+|3|`),
  weapons: weapons(
    `Thump Gun [ANTI-MONSTER/VEHICLE 4+]|18"|3|5+|6|0|2`,
    `Big Chompa's Jaws [ANTI-MONSTER/VEHICLE 3+, EXTRA ATTACKS]|Melee|3|3+|7|-2|4`,
    `Gutrippa - Standard [CLEAVE 1]|Melee|6|2+|9|-2|2`,
    `Gutrippa - Hunter [LETHAL HITS]|Melee|6|2+|12|-2|D6+1`,
  ),
  abilities: [
    core('Feel No Pain 5+'), armyRule('Waaagh!'),
    ability('One Last Kill', `In the Fight phase, when this unit is destroyed, if it has not been selected to fight this phase, roll one D6: on a 2+, do not remove this unit from the battlefield. When this unit has fought, or at the end of the phase (whichever comes first), this unit is removed from the battlefield.`),
    ability('Da Bigger Dey Iz...', `This model's melee attacks that target a ${kwb('MONSTER')} or ${kwb('VEHICLE')} unit can re-roll wound rolls.`, { effects: { rerollAllWounds: true }, combatType: 'melee', requiresTargetKeyword: 'MONSTER' }),
    ability('Beast Snagga Following', `While this model is within 3" of a friendly ${kwb('BEAST SNAGGA')} unit (excluding ${kwb('MONSTER CHARACTER')} units), this model has Lone Operative.`),
  ],
  keywords: ['Monster', 'Beast Snagga', 'Character', 'Epic Hero'],
  unitComposition: ['1 Mozrog Skragbad'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: "big chompa's jaws", count: 1 }, { name: 'gutrippa', count: 1 }, { name: 'thump gun', count: 1 }],
}),

datasheet({
  name: 'Beastboss on Squigosaur', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Beastchoppa; Slugga; Squigosaur's Jaws.`,
  models: models(`Beastboss on Squigosaur|10"|9|3+|5+|10|6+|3|`),
  weapons: weapons(
    `Slugga [CLOSE-QUARTERS, LETHAL HITS: non-MONSTER/VEHICLE]|12"|1|5+|4|0|1`,
    `Thump Gun [ANTI-MONSTER/VEHICLE 4+]|18"|3|5+|6|0|2`,
    `Beastchoppa - Standard [CLEAVE 1]|Melee|6|2+|6|-2|2`,
    `Beastchoppa - Hunter|Melee|6|2+|12|-2|6`,
    `Squigosaur's Jaws [ANTI-MONSTER/VEHICLE 3+, EXTRA ATTACKS]|Melee|3|3+|7|-2|3`,
  ),
  options: [{ button: '•', description: 'This model can be equipped with 1 Thump Gun.' }],
  abilities: [
    core('Feel No Pain 5+'), armyRule('Da Boss'), armyRule('Waaagh!'),
    ability('Thundering Stampede', `(Aura): While a friendly ${kwb('BEAST SNAGGA')} unit is within 6" of this unit, that unit has +1 to charge rolls.`, { appliesToNearby: true }),
    ability("Keep Huntin'!", `(Once per battle round, per army): In your Movement phase, at the start or end of this unit's move, you can select one friendly ${kwb('BEAST SNAGGA')} unit within 6" of this unit. That unit is no longer battle-shocked and is riled up until the start of your next turn.`),
    ability('Boss of da Hunt', `While this model is within 3" of a friendly ${kwb('BEAST SNAGGA')} unit (excluding ${kwb('MONSTER CHARACTER')} units), this model has Lone Operative.`),
  ],
  keywords: ['Monster', 'Beast Snagga', 'Character', 'Warboss'],
  unitComposition: ['1 Beastboss on Squigosaur'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'beastchoppa', count: 1 }, { name: 'slugga', count: 1 }, { name: "squigosaur's jaws", count: 1 }],
}),

datasheet({
  name: 'Weirdboy', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Power Vomit; Copper Staff.`,
  models: models(`Weirdboy|6"|5|5+||4|7+|1|`),
  weapons: weapons(
    `Power Vomit [BLAST 1, HAZARDOUS, PSYCHIC, TORRENT]|12"|3|-|5|-3|2`,
    `Copper Staff [PSYCHIC]|Melee|3|3+|8|-1|2`,
  ),
  abilities: [
    core('Deadly Demise D3'), core('Support'), armyRule('Unstable Energies'), armyRule('Waaagh!'),
    ability('Waaagh! Energy', `(Psyker level 1): This model has the following psychic abilities.<br><br><b>Da Jump</b> (psychic level 1, once per army, per battle round): In your Movement phase, if this unit is not battle-shocked, you can make a psychic roll for this unit by rolling one D6. If you do, on a 1 this unit is battle-shocked; otherwise, select one other friendly ${kwb('ORKS')} unit and place it into strategic reserves, and it can then be set up on the battlefield using Deep Strike.<br><br><b>Warpath</b> (psychic level 1): In the Fight phase, when this unit is selected to fight, if this unit is not battle-shocked, you can make a psychic roll for this unit by rolling one D6. If you do, on a 1 this unit is battle-shocked; otherwise this unit's melee attacks can re-roll wound rolls of 1 and have ${kwb('[PSYCHIC]')}.`),
  ],
  keywords: ['Infantry', 'Character', 'Psyker'],
  unitComposition: ['1 Weirdboy'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'power vomit', count: 1 }, { name: 'copper staff', count: 1 }],
}),

datasheet({
  name: 'Boss Snikrot', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Mork's Teef; Slugga.`,
  models: models(`Boss Snikrot|6"|5|5+|5+|6|6+|1|`),
  weapons: weapons(
    `Slugga [CLOSE-QUARTERS, LETHAL HITS: non-MONSTER/VEHICLE, PRECISION]|12"|1|5+|4|0|1`,
    `Mork's Teef [ANTI-INFANTRY 2+, PRECISION]|Melee|6|2+|6|-2|2`,
  ),
  abilities: [
    core('Infiltrators'), core('Leader'), core('Lone Operative'), core('Stealth'), armyRule('Waaagh!'),
    ability("Kunnin' Infiltrator", `At the end of your opponent's Fight phase, if every model in this unit is hidden and this unit is unengaged, you can place this unit into strategic reserves.`),
    ability('Deff from the Shadows', `(From the first battle round onwards): At the end of your opponent's Movement phase, if this unit is in strategic reserves, this unit can made an ingress move.`),
  ],
  keywords: ['Infantry', 'Character', 'Epic Hero', 'Explosives', 'Smoke'],
  unitComposition: ['1 Boss Snikrot'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: "mork's teef", count: 1 }, { name: 'slugga', count: 1 }],
}),

datasheet({
  name: 'Bannernob', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Kustom Choppa; Shoota.`,
  models: models(`Bannernob|6"|5|4+||4|7+|3|`),
  weapons: weapons(
    `Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 1]|18"|2|5+|4|0|1`,
    `Kustom Choppa|Melee|4|3+|5|-2|2`,
  ),
  abilities: [
    core('Support'), armyRule('Waaagh!'),
    ability("Waaagh! Banner", `This unit has +1 to charge rolls.`),
  ],
  keywords: ['Infantry', 'Character'],
  unitComposition: ['1 Bannernob'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'kustom choppa', count: 1 }, { name: 'shoota', count: 1 }],
}),

datasheet({
  name: 'Bigboss', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Big Choppa; Slugga.`,
  models: models(`Bigboss|6"|5|4+||5|7+|1|`),
  weapons: weapons(
    `Slugga [CLOSE-QUARTERS, LETHAL HITS: non-MONSTER/VEHICLE]|12"|1|5+|4|0|1`,
    `Big Choppa [PRECISION]|Melee|5|3+|7|-2|2`,
  ),
  abilities: [
    core('Support'), armyRule('Waaagh!'),
    ability("Sumfin' to Prove", `This model's melee attacks have +1 to hit rolls.`, { effects: { hitMod: 1 }, combatType: 'melee', bearerOnly: true }),
  ],
  keywords: ['Infantry', 'Character'],
  unitComposition: ['1 Bigboss'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'big choppa', count: 1 }, { name: 'slugga', count: 1 }],
}),

datasheet({
  name: 'Painboy', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Dok's Toolz; 'Urty Syringe.`,
  models: models(`Painboy|6"|5|5+||3|7+|1|`),
  weapons: weapons(
    `'Urty Syringe [ANTI-INFANTRY 4+, DEVASTATING WOUNDS: INFANTRY, EXTRA ATTACKS]|Melee|1|3+|2|0|6`,
    `Dok's Toolz|Melee|3|3+|10|-2|2`,
  ),
  abilities: [
    core('Support'), armyRule('Waaagh!'),
    ability('Crude Surgery', `In your Command phase, this unit heals 3 wounds.`),
    ability('Catch Dat Red Bit', `(Once per battle, per unit): when this model uses its Crude Surgery ability, you can add D3 to the number of wounds healed.`),
  ],
  keywords: ['Infantry', 'Character'],
  unitComposition: ['1 Painboy'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: "dok's toolz", count: 1 }, { name: "'urty syringe", count: 1 }],
}),

datasheet({
  name: 'Painboss', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Beast Snagga Klaw.`,
  models: models(`Painboss|6"|5|4+|6+|4|7+|1|`),
  weapons: weapons(
    `Beast Snagga Klaw [ANTI-MONSTER/VEHICLE 4+]|Melee|3|3+|10|-2|2`,
  ),
  abilities: [
    core('Support'), armyRule('Waaagh!'),
    ability('Push Dat Bit Back In', `(Once per battle, per unit): In your Command phase, select one friendly ${kwb('BEAST SNAGGA')} unit within 6" of this unit. That unit heals 3 wounds.`),
    ability('Hardy Bioniks', `Attacks that target this unit with a Strength characteristic greater than this unit's Toughness characteristic have -1 to wound rolls.`, { effects: { woundMod: -1 }, target: 'defender', requiresAttackerKeyword: '' }),
    ability("Runnin' wiv da Herd", `While this model is attached to a ${kwb('MOUNTED')} unit, this model does not have the ${kwb('INFANTRY')} keyword, has the ${kwb('MOBILE')} and ${kwb('MOUNTED')} keywords, and has +4" M.`),
  ],
  keywords: ['Infantry', 'Beast Snagga', 'Character'],
  unitComposition: ['1 Painboss'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'beast snagga klaw', count: 1 }],
}),

datasheet({
  name: 'Gretchin', role: 'Battleline',
  loadout: `<b>Every model is equipped with:</b> Scavenged Shivs; Grot Blasta.`,
  models: models(`Gretchin|6"|2|6+||1|8+|1|`),
  weapons: weapons(
    `Grot Blasta [CLOSE-QUARTERS]|12"|1|4+|3|0|1`,
    `Scavenged Shivs|Melee|1|5+|2|0|1`,
  ),
  abilities: [
    armyRule('Waaagh!'),
    ability('Downtrodden', `Each Grot Oiler-like transport capacity calculation for this unit treats every 2 ${kwb('GRETCHIN')} models (rounding up) as 1 model.`),
    ability('Thievin' + " Scavengers", `At the end of your Movement phase, if this unit is controlling an objective marker, that objective marker is secured.`),
  ],
  keywords: ['Infantry', 'Grots'],
  unitComposition: ['10-20 Gretchin'], modelCountMin: 10, modelCountMax: 20,
  defaultWeaponNames: [{ name: 'scavenged shivs', count: 20 }, { name: 'grot blasta', count: 20 }],
}),

datasheet({
  name: 'Runtherd', role: 'Characters',
  loadout: `<b>This model is equipped with:</b> Runtherd's Toolz; Slugga.`,
  models: models(`Runtherd|6"|5|5+||3|7+|1|`),
  weapons: weapons(
    `Slugga [CLOSE-QUARTERS, LETHAL HITS: non-MONSTER/VEHICLE]|12"|1|5+|4|0|1`,
    `Runtherd's Toolz|Melee|3|3+|5|0|1`,
  ),
  abilities: [
    core('Support'), armyRule('Waaagh!'),
    ability("That'll Learn Ya", `(Once per battle round, per unit): When this unit becomes battle-shocked, if it has 4+ ${kwb('GRETCHIN')} models, you can select one of the following: any number of Gretchin models in this unit are destroyed; or this unit is no longer battle-shocked.`),
  ],
  keywords: ['Infantry', 'Character'],
  unitComposition: ['1 Runtherd'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: "runtherd's toolz", count: 1 }, { name: 'slugga', count: 1 }],
}),

datasheet({
  name: 'Boyz', role: 'Battleline',
  loadout: `<b>Every Nob is equipped with:</b> Kustom Choppa; Kombi-skorcha.<br><b>Every Boy is equipped with:</b> Choppa; Shoota; Slugga.`,
  models: models(`Boy|6"|5|5+||1|7+|2|`, `Nob|6"|5|5+||3|7+|2|`),
  weapons: weapons(
    `Big Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|36"|3|5+|4|0|1`,
    `Burna [BLAST 1, TORRENT]|12"|3|-|4|0|1`,
    `Kombi-rokkit - Busta Rokkit|24"|1|5+|10|-2|3`,
    `Kombi-rokkit - Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 1]|18"|2|5+|4|0|1`,
    `Kombi-skorcha - Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 1]|18"|2|5+|4|0|1`,
    `Kombi-skorcha - Skorcha [BLAST 1, TORRENT]|12"|3|-|5|0|1`,
    `Kustom Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|18"|4|5+|4|0|1`,
    `Rokkit Launcha - Blasta [BLAST 2]|24"|2|5+|4|0|1`,
    `Rokkit Launcha - Busta|24"|2|5+|10|-2|3`,
    `Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 1]|18"|2|5+|4|0|1`,
    `Slugga [CLOSE-QUARTERS, LETHAL HITS: non-MONSTER/VEHICLE]|12"|1|5+|4|0|1`,
    `Big Choppa [CLEAVE 2]|Melee|4|3+|7|-1|2`,
    `Choppa|Melee|3|3+|5|-1|1`,
    `Kustom Choppa|Melee|4|3+|5|-2|2`,
    `Power Klaw|Melee|3|3+|10|-2|2`,
  ),
  options: [
    { button: '•', description: "Any number of Nobs' Kustom Choppa and Kombi-skorcha can be replaced with 1 Big Choppa." },
    { button: '•', description: "Any number of Nobs' Kustom Choppa can be replaced with 1 Power Klaw." },
    { button: '•', description: "Any number of Nobs' Kombi-skorcha can be replaced with 1 Kombi-rokkit or 1 Kustom Shoota." },
    { button: '•', description: "For every 10 models in this unit, 1 Boy's Shoota can be replaced with 1 Big Shoota, 1 Rokkit Launcha or 1 Burna." },
  ],
  abilities: [
    armyRule('Waaagh!'),
    ability('Ammo Runts', `(Once per battle, per unit): In your Shooting phase, when this unit is selected to shoot, this unit's ranged attacks have +1 to hit rolls.`, { effects: { hitMod: 1 }, combatType: 'ranged' }),
    ability('Tide of Muscle', `In the Fight phase, if this unit made a charge move this turn, this unit's melee attacks have ${kwb('[LETHAL HITS]')}.`, { effects: { lethalHitsBonus: true }, combatType: 'melee' }),
    ability('Never Too Busy to Fight', `This unit being engaged does not prevent it from being eligible to start an action.`),
  ],
  keywords: ['Infantry', 'Battleline', 'Explosives', 'Mob'],
  unitComposition: ['1-2 Nobz', '9-18 Boyz'], modelCountMin: 10, modelCountMax: 20,
  defaultWeaponNames: [{ name: 'kustom choppa', count: 1 }, { name: 'kombi-skorcha', count: 1 }, { name: 'choppa', count: 9 }, { name: 'shoota', count: 9 }, { name: 'slugga', count: 9 }],
}),

datasheet({
  name: 'Beast Snagga Boyz', role: 'Battleline',
  loadout: `<b>Every Nob is equipped with:</b> Power Snappa; Slugga.<br><b>Every Beast Snagga Boy is equipped with:</b> Choppa; Slugga.`,
  models: models(`Beast Snagga Boy|6"|5|5+||1|7+|2|`, `Nob|6"|5|5+|6+|3|7+|2|`),
  weapons: weapons(
    `Slugga [CLOSE-QUARTERS, LETHAL HITS: non-MONSTER/VEHICLE]|12"|1|5+|4|0|1`,
    `Thump Gun [ANTI-MONSTER/VEHICLE 4+]|18"|3|5+|6|0|2`,
    `Choppa - Standard|Melee|3|3+|5|-1|1`,
    `Choppa - Hunter|Melee|3|3+|6|-2|1`,
    `Power Snappa [ANTI-MONSTER/VEHICLE 4+]|Melee|3|3+|8|-2|2`,
  ),
  options: [{ button: '•', description: 'For every 10 models in this unit, 1 Beast Snagga Boy can be equipped with 1 Thump Gun.' }],
  abilities: [
    armyRule('Waaagh!'),
    ability('Mobbed', `When this unit ends a charge move, each enemy ${kwb('MONSTER')} or ${kwb('VEHICLE')} unit engaged with this unit must make a battle-shock roll, with -1 to that roll, or -2 if this unit has 13+ models.`),
  ],
  keywords: ['Infantry', 'Battleline', 'Beast Snagga', 'Mob'],
  unitComposition: ['1-2 Nobz', '9-18 Beast Snagga Boyz'], modelCountMin: 10, modelCountMax: 20,
  defaultWeaponNames: [{ name: 'power snappa', count: 1 }, { name: 'slugga', count: 10 }, { name: 'choppa', count: 9 }],
}),

datasheet({
  name: 'Meganobz', role: 'Battleline',
  loadout: `<b>Every model is equipped with:</b> Kustom Shoota; Power Klaw.`,
  models: models(`Meganob|5"|6|2+||3|7+|1|`),
  weapons: weapons(
    `Kombi-weapon - Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 1]|18"|2|5+|4|0|1`,
    `Kombi-weapon - Kill Shot|24"|1|5+|10|-2|3`,
    `Kombi-weapon - Point Blank [BLAST 1, TORRENT]|12"|3|-|5|0|1`,
    `Kustom Shoota - Aimed [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|18"|4|5+|4|0|1`,
    `Kustom Shoota - Point Blank [CLOSE-QUARTERS, TORRENT]|6"|D3+3|-|4|0|1`,
    `Killsaw|Melee|3|4+|10|-2|3`,
    `Power Klaw|Melee|3|3+|10|-2|2`,
    `Twin Killsaws [TWIN-LINKED]|Melee|3|4+|10|-2|3`,
  ),
  options: [
    { button: '•', description: "Any model's Power Klaw can be replaced with 1 Killsaw." },
    { button: '•', description: "Any model's Kustom Shoota can be replaced with 1 Kombi-weapon." },
    { button: '•', description: "Any model's Power Klaw and Kustom Shoota can be replaced with 1 Twin Killsaws." },
  ],
  abilities: [
    armyRule('Waaagh!'),
    ability('Arrogant Invulnerability', `Attacks that target this unit have -1 AP.`, { effects: { apMod: -1 }, target: 'defender' }),
    ability("Krumpin' Time", `In the Fight phase, while this unit is riled up, this unit's melee attacks have +1 to hit rolls.`, { effects: { hitMod: 1 }, combatType: 'melee' }),
  ],
  keywords: ['Infantry', 'Battleline', 'Explosives', 'Mega Armour'],
  unitComposition: ['2-6 Meganobz'], modelCountMin: 2, modelCountMax: 6,
  defaultWeaponNames: [{ name: 'kustom shoota', count: 2 }, { name: 'power klaw', count: 2 }],
}),

datasheet({
  name: 'Nobz', role: 'Other Datasheets',
  loadout: `<b>Every model is equipped with:</b> Kustom Krumpa; Kustom Shoota.`,
  models: models(`Nob|6"|5|4+||3|7+|1|`),
  weapons: weapons(
    `Big Skorcha [BLAST 2, TORRENT]|18"|3|-|5|-1|1`,
    `Kustom Big Shoota [LETHAL HITS: non-MONSTER/VEHICLE]|18"|8|5+|4|0|1`,
    `Kombi-rokkit - Busta Rokkit|24"|1|5+|10|-2|3`,
    `Kombi-rokkit - Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 1]|18"|2|5+|4|0|1`,
    `Kustom Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|18"|4|5+|4|0|1`,
    `Big Choppa [CLEAVE 2]|Melee|4|3+|7|-1|2`,
    `Kustom Choppa|Melee|4|3+|5|-2|2`,
    `Kustom Krumpa|Melee|3|3+|10|-2|2`,
  ),
  options: [
    { button: '•', description: 'For every 5 models in this unit, 1 Kustom Krumpa and Kustom Shoota can be replaced with 1 Big Skorcha and 1 Kustom Choppa, or 1 Kustom Big Shoota and 1 Kustom Choppa, or 1 Big Choppa.' },
    { button: '•', description: '(Wargear ability) For every 5 models in this unit, 1 Kustom Shoota can be replaced with 1 Paired Krumpas.' },
    { button: '•', description: 'Any number of models can each have their Kustom Shoota replaced with 1 Kombi-rokkit.' },
  ],
  abilities: [
    armyRule('Waaagh!'),
    ability('Get Out da Way!', `While making a charge move, this unit can move through models (excluding ${kwb('MONSTER')} and ${kwb('VEHICLE')} models).`),
    ability('Ammo Runts', `(Once per battle, per unit): In your Shooting phase, when this unit is selected to shoot, this unit's ranged attacks have +1 to hit rolls.`, { effects: { hitMod: 1 }, combatType: 'ranged' }),
    ability('Paired Krumpas', `(Wargear ability): Attacks made with this model's Kustom Krumpa weapon can re-roll hit rolls and wound rolls.`, { effects: { rerollAllHits: true, rerollAllWounds: true }, combatType: 'melee', bearerOnly: true }),
  ],
  keywords: ['Infantry', 'Explosives'],
  unitComposition: ['5-10 Nobz'], modelCountMin: 5, modelCountMax: 10,
  defaultWeaponNames: [{ name: 'kustom krumpa', count: 5 }, { name: 'kustom shoota', count: 5 }],
}),

datasheet({
  name: 'Kommandos', role: 'Other Datasheets',
  loadout: `<b>Every model is equipped with:</b> Choppa; Slugga.`,
  models: models(`Kommando|6"|5|5+||1|7+|1|`, `Nob|6"|5|5+||3|7+|1|`),
  weapons: weapons(
    `Burna [BLAST 1, TORRENT]|12"|3|-|4|0|1`,
    `Kustom Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|18"|4|5+|4|0|1`,
    `Rokkit Launcha - Blasta [BLAST 2]|24"|2|5+|4|0|1`,
    `Rokkit Launcha - Busta|24"|2|5+|10|-2|3`,
    `Slugga [CLOSE-QUARTERS, LETHAL HITS: non-MONSTER/VEHICLE]|12"|1|5+|4|0|1`,
    `Big Choppa [CLEAVE 2]|Melee|4|3+|7|-1|2`,
    `Breacha Ram|Melee|2|4+|8|-2|2`,
    `Choppa|Melee|3|3+|5|-1|1`,
    `Power Klaw|Melee|3|3+|10|-2|2`,
  ),
  options: [
    { button: '•', description: "The Nob's Choppa can be replaced with 1 Big Choppa or 1 Power Klaw." },
    { button: '•', description: '1 Kommando model can be equipped with 1 Burna.' },
    { button: '•', description: '1 Kommando model can be equipped with 1 Rokkit Launcha.' },
    { button: '•', description: "1 Kommando model's Choppa can be replaced with 1 Breacha Ram." },
    { button: '•', description: 'Up to 2 Kommando models can each be equipped with 1 Kustom Shoota.' },
  ],
  abilities: [
    core('Infiltrators'), core('Stealth'), armyRule('Waaagh!'),
    ability("Found 'Em!", `In your Movement phase, you can select one enemy unit within 12" of this unit. That unit has +3" detection range until the end of the turn.`),
    ability('Taktikal Know-wotz', `During the Declare Battle Formations step, you can split this unit into two units, each with a starting strength of 5. If you do, select which of those units has the Bomb Squig ability and which has the Found 'Em! ability.`),
    ability('Nowhere to Hide', `This unit's attacks that target a hidden unit have +1 to hit rolls.`, { effects: { hitMod: 1 } }),
    ability('Bomb Squig', `(Once per battle, per unit): In your Movement phase, when this unit ends a normal move, you can select one visible enemy unit within 12" of this unit and roll one D6: on a 3+, that enemy unit suffers D3 mortal wounds.`),
  ],
  keywords: ['Infantry', 'Explosives', 'Smoke'],
  unitComposition: ['1 Nob', '9 Kommandos'], modelCountMin: 10, modelCountMax: 10,
  defaultWeaponNames: [{ name: 'choppa', count: 10 }, { name: 'slugga', count: 10 }],
}),

datasheet({
  name: 'Flash Gitz', role: 'Other Datasheets',
  loadout: `<b>Every model is equipped with:</b> Choppa; Snazzgun.`,
  models: models(`Flash Git|6"|5|4+||3|7+|1|`),
  weapons: weapons(
    `Snazzgun - Cutta [HAZARDOUS, MELTA 2]|12"|1|4+|9|-3|D3+2`,
    `Snazzgun - Dakka [LETHAL HITS: non-MONSTER/VEHICLE, SUSTAINED HITS 1]|24"|3|4+|6|-1|2`,
    `Snazzgun - Kill Shot [HAZARDOUS]|36"|2|4+|8|-2|2`,
    `Choppa|Melee|4|3+|5|-1|1`,
  ),
  abilities: [
    armyRule('Waaagh!'),
    ability('Finderz Keeperz', `In your Shooting phase, if this unit or the target of this unit's attack is within range of an objective marker, this unit's ranged attacks have +1 AP.`, { effects: { apMod: 1 }, combatType: 'ranged' }),
  ],
  keywords: ['Infantry', 'Explosives'],
  unitComposition: ['1 Kaptin', '4-9 Flash Gitz'], modelCountMin: 5, modelCountMax: 10,
  defaultWeaponNames: [{ name: 'choppa', count: 5 }, { name: 'snazzgun', count: 5 }],
}),

datasheet({
  name: 'Stormboyz', role: 'Other Datasheets',
  loadout: `<b>The Nob is equipped with:</b> Kustom Choppa; Slugga.<br><b>Every Stormboy is equipped with:</b> Choppa; Slugga.`,
  models: models(`Stormboy|12"|5|5+||1|7+|1|`, `Nob|12"|5|5+||3|7+|1|`),
  weapons: weapons(
    `Slugga [CLOSE-QUARTERS, LETHAL HITS: non-MONSTER/VEHICLE]|12"|1|5+|4|0|1`,
    `Choppa|Melee|3|3+|5|-1|1`,
    `Kustom Choppa|Melee|4|3+|5|-2|2`,
    `Power Klaw|Melee|3|3+|10|-2|2`,
  ),
  options: [{ button: '•', description: "The Nob's Kustom Choppa can be replaced with 1 Power Klaw." }],
  abilities: [
    core('Deep Strike'), armyRule('Waaagh!'),
    ability('Rokkit Charge', `In the Fight phase, when this unit is selected to fight, if this unit made a charge move this turn, you can use this ability. If you do, this unit's melee attacks have +1 A, +1 S and ${kwb('[HAZARDOUS]')}.`, { effects: { attacksMod: 1, strengthMod: 1 }, combatType: 'melee' }),
  ],
  keywords: ['Infantry', 'Explosives', 'Fly', 'Jump Pack'],
  unitComposition: ['1 Nob', '4-9 Stormboyz'], modelCountMin: 5, modelCountMax: 10,
  defaultWeaponNames: [{ name: 'kustom choppa', count: 1 }, { name: 'choppa', count: 9 }, { name: 'slugga', count: 10 }],
}),

datasheet({
  name: 'Breaka Boyz', role: 'Other Datasheets',
  loadout: `<b>The Nob is equipped with:</b> Choppa; Rokkit Pistol; Smash Hammer.<br><b>Every Breaka Boy is equipped with:</b> Smash Hammer.`,
  models: models(`Breaka Boy|6"|5|4+||2|7+|1|`, `Nob|6"|5|4+||3|7+|1|`),
  weapons: weapons(
    `Rokkit Pistol [CLOSE-QUARTERS]|12"|1|5+|10|-2|3`,
    `Choppa|Melee|4|3+|5|-1|1`,
    `Knucklebustas [ANTI-MONSTER/VEHICLE 4+]|Melee|4|3+|5|-2|2`,
    `Smash Hammer - Standard|Melee|3|3+|7|-2|2`,
    `Smash Hammer - Hunter|Melee|3|3+|12|-2|3`,
    `Tankhammer [DEVASTATING WOUNDS, HAZARDOUS]|Melee|3|4+|12|-2|3`,
  ),
  options: [
    { button: '•', description: "The Nob's Smash Hammer can be replaced with 1 Rokkit Pistol." },
    { button: '•', description: "1 Breaka Boy's Smash Hammer can be replaced with 1 Knucklebustas." },
    { button: '•', description: "1 Breaka Boy's Smash Hammer can be replaced with 1 Tankhammer." },
  ],
  abilities: [
    armyRule('Waaagh!'),
    ability('Bomb Squigs', `(Once per turn, twice per battle, per unit): In your Movement phase, when this unit ends a normal move, you can select one visible enemy unit within 12" of this unit and roll one D6: on a 3+, that enemy unit suffers D3 mortal wounds.`),
    ability('Trophy Hunters', `This unit has +1 to charge rolls.`),
  ],
  keywords: ['Infantry', 'Explosives'],
  unitComposition: ['1 Nob', '5 Breaka Boyz'], modelCountMin: 6, modelCountMax: 6,
  defaultWeaponNames: [{ name: 'choppa', count: 1 }, { name: 'rokkit pistol', count: 1 }, { name: 'smash hammer', count: 6 }],
}),

datasheet({
  name: 'Mek Gunz', role: 'Other Datasheets',
  loadout: `<b>Every model is equipped with:</b> Scavenged Shivs; Smasha Gun.`,
  models: models(`Mek Gun|5"|6|4+|6+|6|8+|2|`),
  weapons: weapons(
    `Bubblechukka [BLAST 3, LETHAL HITS]|48"|8|4+|3|-3|1`,
    `Kustom Mega-kannon [BLAST 1, HAZARDOUS]|36"|D3+1|4+|12|-2|4`,
    `Smasha Gun [BLAST 1]|48"|4|4+|7|-3|3`,
    `Traktor Kannon [ANTI-FLY 2+]|48"|2|4+|6|-2|D3+3`,
    `Scavenged Shivs|Melee|5|5+|2|0|1`,
  ),
  options: [{ button: '•', description: "Any number of models can each have their Smasha Gun replaced with 1 Bubblechukka, 1 Kustom Mega-kannon or 1 Traktor Kannon." }],
  abilities: [
    armyRule('Waaagh!'),
    ability('Madcap Artillery', `In your Shooting phase, when this unit has shot, if all ranged weapons equipped by each Mek Gunz model in this unit are the same, select one enemy unit hit by those attacks. That unit has the ability below matching that weapon's name until the start of your next turn.<br><ul><li><b>Bubblechukka:</b> that unit is wobbled — while a wobbled unit is attacking, its targets have the benefit of cover against those attacks.</li><li><b>Kustom Mega-kannon:</b> that unit is zapped — while a unit is zapped, it has -1 Ld.</li><li><b>Smasha Gun:</b> that unit is smashed — while a unit is smashed, it has -2" M.</li><li><b>Traktor Kannon:</b> that unit is grounded — while a unit is grounded, it cannot take to the skies.</li></ul>`),
  ],
  keywords: ['Vehicle', 'Frame', 'Grots'],
  unitComposition: ['1-3 Mek Gunz'], modelCountMin: 1, modelCountMax: 3,
  defaultWeaponNames: [{ name: 'scavenged shivs', count: 1 }, { name: 'smasha gun', count: 1 }],
}),

datasheet({
  name: 'Tankbustas', role: 'Other Datasheets',
  loadout: `<b>The Nob is equipped with:</b> Choppa; 2 Rokkit Pistol.<br><b>Every Tankbusta is equipped with:</b> Busta Rokkit Launcha; Gitstikka.`,
  models: models(`Tankbusta|6"|5|4+||2|7+|1|`, `Nob|6"|5|4+||3|7+|1|`),
  weapons: weapons(
    `Busta Rokkit Launcha - Standard|24"|2|4+|10|-2|3`,
    `Busta Rokkit Launcha - Hunter|24"|3|4+|12|-2|3`,
    `Rokkit Pistol [CLOSE-QUARTERS]|12"|1|4+|10|-2|3`,
    `Choppa|Melee|4|3+|5|-1|1`,
    `Gitstikka|Melee|3|3+|5|0|1`,
    `Smash Hammer - Standard|Melee|3|3+|7|-2|2`,
    `Smash Hammer - Hunter|Melee|3|3+|12|-2|3`,
  ),
  options: [
    { button: '•', description: "The Nob's Rokkit Pistol can be replaced with 1 Smash Hammer." },
    { button: '•', description: '1 Tankbusta model can be equipped with 1 Busta Rokkit Launcha or (wargear ability) 1 Pulsa Rokkit.' },
  ],
  abilities: [
    armyRule('Waaagh!'),
    ability('Rokkit Barrage', `In your Shooting phase, when this unit has shot, select one enemy unit hit by those attacks. That unit must make a battle-shock roll, with -1 to that roll.`),
    ability('Bomb Squigs', `(Once per turn, twice per battle, per unit): In your Movement phase, when this unit ends a normal move, you can select one visible enemy unit within 12" of this unit and roll one D6: on a 3+, that enemy unit suffers D3 mortal wounds.`),
    ability('Pulsa Rokkit', `(Once per battle, per unit, wargear ability): In your Shooting phase, when this unit is selected to shoot, you can select one enemy ${kwb('MONSTER')} or ${kwb('VEHICLE')} unit within 24" of this unit. This unit's attacks that target that unit have +1 AP and ${kwb('[LETHAL HITS]')} until the end of the phase.`, { effects: { apMod: 1, lethalHitsBonus: true }, combatType: 'ranged', requiresTargetKeyword: 'MONSTER' }),
  ],
  keywords: ['Infantry', 'Explosives'],
  unitComposition: ['1 Nob', '5 Tankbustas'], modelCountMin: 6, modelCountMax: 6,
  defaultWeaponNames: [{ name: 'choppa', count: 1 }, { name: 'rokkit pistol', count: 2 }, { name: 'busta rokkit launcha', count: 5 }, { name: 'gitstikka', count: 5 }],
}),

datasheet({
  name: 'Warbikers', role: 'Other Datasheets',
  loadout: `<b>The Biker Nob is equipped with:</b> Kustom Choppa; Dual Kombi-rokkit.<br><b>Every Warbiker is equipped with:</b> Choppa; Dual Dakkagun.`,
  models: models(`Warbiker|12"|6|4+||3|7+|2|`, `Biker Nob|12"|6|4+|6+|4|7+|2|`),
  weapons: weapons(
    `Dual Kombi-rokkit - Dakkagun [ASSAULT, LETHAL HITS: non-MONSTER/VEHICLE]|18"|6|5+|5|0|1`,
    `Dual Kombi-rokkit - Busta Rokkit [ASSAULT]|24"|2|5+|10|-2|3`,
    `Dual Dakkagun [ASSAULT, LETHAL HITS: non-MONSTER/VEHICLE]|18"|6|5+|5|0|1`,
    `Choppa|Melee|3|3+|5|-1|1`,
    `Kustom Choppa|Melee|4|3+|5|-2|2`,
  ),
  abilities: [
    armyRule('Waaagh!'),
    ability('High-speed Carnage', `If this unit made a charge move this turn, this unit's melee attacks have +1 S and +1 D.`, { effects: { strengthMod: 1, damageMod: 1 }, combatType: 'melee' }),
  ],
  keywords: ['Mounted', 'Explosives', 'Speed Freeks'],
  unitComposition: ['1 Biker Nob', '2-5 Warbikers'], modelCountMin: 3, modelCountMax: 6,
  defaultWeaponNames: [{ name: 'kustom choppa', count: 1 }, { name: 'choppa', count: 2 }, { name: 'dual dakkagun', count: 2 }, { name: 'dual kombi-rokkit', count: 1 }],
}),

datasheet({
  name: 'Wartrakks', role: 'Other Datasheets',
  loadout: `<b>Every model is equipped with:</b> Kustom Choppa; Kustom Shoota; Multi-busta Launcha.`,
  models: models(`Wartrakk|12"|6|4+|6+|7|7+|3|`),
  weapons: weapons(
    `Kustom Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|18"|4|5+|4|0|1`,
    `Multi-busta Launcha|24"|D3+3|5+|10|-2|3`,
    `Kustom Choppa|Melee|4|3+|5|-2|2`,
  ),
  abilities: [
    armyRule('Waaagh!'),
    ability('Speednob Support', `While each model in this unit is within 3" of a friendly ${kwb('SPEED FREEKS')} unit (excluding ${kwb('WARTRAKK')} units), this unit has Lone Operative.`),
    ability("Bust 'Em", `In your Shooting phase, when this unit has shot, select one enemy unit hit by those attacks. That unit is busted until the end of the turn — friendly ${kwb('SPEED FREEKS')} units' attacks that target a busted unit have ${kwb('[LETHAL HITS]')}.`),
  ],
  keywords: ['Mounted', 'Speed Freeks'],
  unitComposition: ['1-2 Wartrakks'], modelCountMin: 1, modelCountMax: 2,
  defaultWeaponNames: [{ name: 'kustom choppa', count: 1 }, { name: 'kustom shoota', count: 1 }, { name: 'multi-busta launcha', count: 1 }],
}),

datasheet({
  name: 'Deffkoptas', role: 'Other Datasheets',
  loadout: `<b>Every model is equipped with:</b> Choppa; Rokkit Launcha; Slugga; Spinnin' Blades.`,
  models: models(`Deffkopta|12"|6|4+|6+|4|7+|2|`),
  weapons: weapons(
    `Rokkit Launcha - Blasta [BLAST 2]|24"|2|5+|4|0|1`,
    `Rokkit Launcha - Busta [LETHAL HITS]|24"|2|5+|10|-2|3`,
    `Kustom Mega-blasta [HAZARDOUS, LETHAL HITS]|24"|3|5+|9|-2|3`,
    `Slugga [CLOSE-QUARTERS, LETHAL HITS: non-MONSTER/VEHICLE]|12"|1|5+|4|0|1`,
    `Choppa|Melee|3|4+|5|-1|1`,
    `Spinnin' Blades [CLEAVE 1, HAZARDOUS]|Melee|4|3+|5|-1|1`,
  ),
  options: [{ button: '•', description: 'For every 3 models in this unit, 1 Rokkit Launcha can be replaced with 1 Kustom Mega-blasta.' }],
  abilities: [
    core('Deep Strike'), armyRule('Waaagh!'),
    ability('Deff from Above', `In your Shooting phase, if this unit made an ingress move this turn, this unit's ranged attacks have +1 to hit rolls.`, { effects: { hitMod: 1 }, combatType: 'ranged' }),
    ability('Aerial Manoover', `At the end of your opponent's Fight phase, if this unit is unengaged, you can place this unit into strategic reserves.`),
  ],
  keywords: ['Mounted', 'Explosives', 'Fly', 'Speed Freeks'],
  unitComposition: ['3-6 Deffkoptas'], modelCountMin: 3, modelCountMax: 6,
  defaultWeaponNames: [{ name: 'choppa', count: 3 }, { name: 'rokkit launcha', count: 3 }, { name: 'slugga', count: 3 }, { name: "spinnin' blades", count: 3 }],
}),

datasheet({
  name: 'Rukkatrukk Squigbuggies', role: 'Other Datasheets',
  loadout: `<b>Every model is equipped with:</b> Saw Blades; Sawn-off Shotgun; Squig Launchas.`,
  models: models(`Rukkatrukk Squigbuggy|12"|7|4+|6+|9|7+|3|`),
  weapons: weapons(
    `Sawn-off Shotgun [ASSAULT, LETHAL HITS: non-MONSTER/VEHICLE]|12"|2|5+|4|0|1`,
    `Squig Launchas [IGNORES COVER]|24"|D6+6|4+|5|-1|2`,
    `Saw Blades [CLEAVE 1]|Melee|4|3+|7|-1|2`,
  ),
  abilities: [
    core('Deadly Demise 1'), armyRule('Waaagh!'),
    ability('Squig Barrage', `In your Shooting phase, when this unit has shot, select one enemy unit (excluding ${kwb('MONSTER')} and ${kwb('VEHICLE')} units) hit by this unit's Squig Launchas weapons. That unit is covered in Squigs until the start of your next turn — while a unit is covered in Squigs, that unit's attacks have -1 to hit rolls.`),
  ],
  keywords: ['Vehicle', 'Explosives', 'Speed Freeks'],
  unitComposition: ['1-2 Rukkatrukk Squigbuggies'], modelCountMin: 1, modelCountMax: 2,
  defaultWeaponNames: [{ name: 'saw blades', count: 1 }, { name: 'sawn-off shotgun', count: 1 }, { name: 'squig launchas', count: 1 }],
}),

datasheet({
  name: 'Warbuggies', role: 'Other Datasheets',
  loadout: `<b>Every model is equipped with:</b> Extra Dakka; Mek Speshul; Spiked Ram.`,
  models: models(`Warbuggy|12"|7|4+|6+|9|7+|3|`),
  weapons: weapons(
    `Extra Dakka [ASSAULT, LETHAL HITS: non-MONSTER/VEHICLE, SUSTAINED HITS 1]|12"|4|5+|5|-1|1`,
    `Rivet Kannon - Aimed [ANTI-INFANTRY 4+, ASSAULT, DEVASTATING WOUNDS: INFANTRY]|24"|6|4+|7|-2|2`,
    `Rivet Kannon - Point Blank [ANTI-INFANTRY 4+, ASSAULT, DEVASTATING WOUNDS: INFANTRY, TORRENT]|6"|D3+1|-|7|-2|2`,
    `Mek Speshul - Aimed [ASSAULT, LETHAL HITS: non-MONSTER/VEHICLE, SUSTAINED HITS 1]|24"|14|4+|5|-1|1`,
    `Mek Speshul - Point Blank [ASSAULT, TORRENT]|6"|2D6+2|-|5|-1|1`,
    `Spiked Ram [CLEAVE 1]|Melee|4|3+|7|-1|2`,
  ),
  options: [{ button: '•', description: "Any number of models' Mek Speshul can be replaced with 1 Rivet Kannon." }],
  abilities: [
    core('Deadly Demise 1'), armyRule('Waaagh!'),
    ability("Drive-by Skorchin'", `In your Movement phase, you can select one visible enemy unit (excluding ${kwb('MONSTER')} and ${kwb('VEHICLE')} units) within 6" of this unit. That enemy unit cannot be targeted with the Fire Overwatch stratagem until the end of the turn.`),
  ],
  keywords: ['Vehicle', 'Explosives', 'Speed Freeks'],
  unitComposition: ['1-2 Warbuggies'], modelCountMin: 1, modelCountMax: 2,
  defaultWeaponNames: [{ name: 'extra dakka', count: 1 }, { name: 'mek speshul', count: 1 }, { name: 'spiked ram', count: 1 }],
}),

datasheet({
  name: 'Squighog Boyz', role: 'Other Datasheets',
  loadout: `<b>Every Nob on Smasha Squig is equipped with:</b> Big Choppa; Slugga; Squig's Jaws.<br><b>Every Squighog Boy is equipped with:</b> Saddlegit's Shiv; Squig's Jaws; Stikka.`,
  models: models(`Squighog Boy|10"|6|4+||3|7+|2|`, `Nob on Smasha Squig|10"|6|4+|6+|4|7+|2|`),
  weapons: weapons(
    `Saddlegit's Shiv [ASSAULT]|9"|1|4+|3|0|1`,
    `Slugga [CLOSE-QUARTERS, LETHAL HITS: non-MONSTER/VEHICLE]|12"|1|5+|4|0|1`,
    `Stikka [ANTI-MONSTER/VEHICLE 4+, ASSAULT]|9"|1|5+|5|-1|2`,
    `Big Choppa [ANTI-MONSTER/VEHICLE 4+, CLEAVE 2]|Melee|4|3+|7|-1|2`,
    `Squig's Jaws [EXTRA ATTACKS]|Melee|3|4+|6|-1|2`,
    `Stikka [ANTI-MONSTER/VEHICLE 4+]|Melee|3|3+|5|-1|2`,
  ),
  abilities: [
    armyRule('Waaagh!'),
    ability('Bomb Squig', `(Once per battle, per unit): In your Movement phase, when this unit ends a normal move, you can select one visible enemy unit within 12" of this unit and roll one D6: on a 3+, that enemy unit suffers D3 mortal wounds.`),
    ability('Brutal Impact', `If this unit made a charge move this turn, this unit's attacks have +1 D.`, { effects: { damageMod: 1 } }),
  ],
  keywords: ['Mounted', 'Beast Snagga', 'Explosives', 'Mobile'],
  unitComposition: ['1-2 Nobz on Smasha Squig', '3-6 Squighog Boyz'], modelCountMin: 4, modelCountMax: 8,
  defaultWeaponNames: [{ name: 'big choppa', count: 1 }, { name: 'slugga', count: 1 }, { name: "saddlegit's shiv", count: 3 }, { name: 'stikka', count: 3 }, { name: "squig's jaws", count: 4 }],
}),

datasheet({
  name: 'Trukk', role: 'Other Datasheets',
  loadout: `<b>This model is equipped with:</b> Dual Big Shoota; Spiked Ram.`,
  models: models(`Trukk|12"|8|4+|6+|10|7+|2|`),
  weapons: weapons(
    `Dual Big Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 4]|36"|6|5+|5|0|1`,
    `Rokkit Launcha - Blasta [BLAST 2]|24"|2|5+|4|0|1`,
    `Rokkit Launcha - Busta|24"|2|5+|10|-2|3`,
    `Buzzsaw [CLEAVE 1, EXTRA ATTACKS]|Melee|2|3+|6|-1|2`,
    `Grabbin' Klaw [EXTRA ATTACKS]|Melee|2|3+|10|-2|2`,
    `Spiked Ram [CLEAVE 1]|Melee|3|3+|6|0|1`,
  ),
  options: [
    { button: '•', description: "This model's Dual Big Shoota can be replaced with 1 Rokkit Launcha." },
    { button: '•', description: 'This model can be equipped with 1 Buzzsaw or 1 Grabbin\' Klaw.' },
  ],
  abilities: [
    core('Deadly Demise D3'), core('Firing Deck 12'), armyRule('Waaagh!'),
    ability("Pilin' Out", `In your opponent's Movement phase, when an enemy unit ends a move within 8" of this model, units embarked within this model can make a disembark move using the rapid disembark mode.`),
    ability('Transport', `This model has a transport capacity of 12 ${kwb('ORKS INFANTRY')} models. It cannot transport ${kwb('GHAZGHKULL THRAKA')} or ${kwb('JUMP PACK')} models. Each ${kwb('MEGA ARMOUR')} model takes up the space of 2 models.`),
  ],
  keywords: ['Vehicle', 'Dedicated Transport', 'Frame', 'Speed Freeks', 'Transport'],
  unitComposition: ['1 Trukk'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'dual big shoota', count: 1 }, { name: 'spiked ram', count: 1 }],
}),

datasheet({
  name: 'Battlewagon', role: 'Other Datasheets',
  loadout: `<b>This model is equipped with:</b> Crushin' Bulk.`,
  models: models(`Battlewagon|10"|11|3+|6+|16|7+|5|`),
  weapons: weapons(
    `Big Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|36"|3|5+|5|0|1`,
    `Crushin' Bulk [CLEAVE 1]|Melee|6|3+|8|-2|2`,
    `Grabbin' Klaw [EXTRA ATTACKS]|Melee|2|3+|10|-2|2`,
    `Wreckin' Ball [CLEAVE 2, EXTRA ATTACKS]|Melee|1|3+|10|0|D6`,
  ),
  options: [
    { button: '•', description: "This model can be equipped with 1 Wreckin' Ball." },
    { button: '•', description: 'This model can be equipped with up to 4 Big Shoota.' },
    { button: '•', description: "This model can be equipped with 1 Grabbin' Klaw." },
  ],
  abilities: [
    core('Deadly Demise D6'), core('Firing Deck 11'), armyRule('Waaagh!'),
    ability('Mobile Fortress', `Ranged attacks that target this unit have -1 D.`, { effects: { damageMod: -1 }, combatType: 'ranged', target: 'defender' }),
    ability('Transport', `This model has a transport capacity of 22 ${kwb('ORKS INFANTRY')} models. Each ${kwb('MEGA ARMOUR')} or ${kwb('JUMP PACK')} model takes up the space of 2 models. Each ${kwb('GHAZGHKULL THRAKA')} model takes up the space of 4 models.`),
  ],
  keywords: ['Vehicle', 'Frame', 'Transport', 'Wagon'],
  unitComposition: ['1 Battlewagon'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: "crushin' bulk", count: 1 }],
  damagedW: 6,
}),

datasheet({
  name: 'Gunwagon', role: 'Other Datasheets',
  loadout: `<b>This model is equipped with:</b> Crushin' Bulk; Kannon.`,
  models: models(`Gunwagon|10"|12|3+|6+|16|7+|5|`),
  weapons: weapons(
    `Big Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|36"|3|5+|5|0|1`,
    `Kannon - Frag [BLAST 3, RAPID FIRE 4]|36"|4|4+|5|0|1`,
    `Kannon - Shell [RAPID FIRE 2]|36"|2|4+|10|-2|D6+1`,
    `Killkannon [ANTI-INFANTRY 3+, BLAST 1, RAPID FIRE 4]|24"|4|4+|6|-3|2`,
    `Lobba [BLAST 3, INDIRECT FIRE]|48"|3|4+|5|0|1`,
    `Zzap Gun [ANTI-MONSTER/VEHICLE 4+, DEVASTATING WOUNDS: MONSTER/VEHICLE, RAPID FIRE 2, SUSTAINED HITS 2]|36"|2|4+|8|-2|4`,
    `Crushin' Bulk [CLEAVE 2]|Melee|6|3+|8|-2|2`,
    `Grabbin' Klaw [EXTRA ATTACKS]|Melee|2|3+|10|-2|2`,
    `Wreckin' Ball [CLEAVE 2, EXTRA ATTACKS]|Melee|1|3+|10|0|D6`,
  ),
  options: [
    { button: '•', description: "This model can be equipped with 1 Wreckin' Ball." },
    { button: '•', description: "This model can be equipped with 1 Grabbin' Klaw." },
    { button: '•', description: 'This model can be equipped with 1 Lobba.' },
    { button: '•', description: 'This model can be equipped with up to 4 Big Shoota.' },
    { button: '•', description: "This model's Kannon can be replaced with 1 Killkannon or 1 Zzap Gun." },
  ],
  abilities: [
    core('Deadly Demise D6'), armyRule('Waaagh!'),
    ability('Mobile Arsenal', `This unit's ranged attacks can re-roll hit rolls of 1.`, { effects: { rerollHitsOf1: true }, combatType: 'ranged' }),
    ability('Transport', `This model has a transport capacity of 12 ${kwb('ORKS INFANTRY')} models. Each ${kwb('MEGA ARMOUR')} or ${kwb('JUMP PACK')} model takes up the space of 2 models. Each ${kwb('GHAZGHKULL THRAKA')} model takes up the space of 4 models.`),
  ],
  keywords: ['Vehicle', 'Frame', 'Transport', 'Wagon'],
  unitComposition: ['1 Gunwagon'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: "crushin' bulk", count: 1 }, { name: 'kannon', count: 1 }],
  damagedW: 6,
}),

datasheet({
  name: 'Hunta Rig', role: 'Other Datasheets',
  loadout: `<b>This model is equipped with:</b> Butcha Boyz; 'Eavy Lobba; Savage Horns and Hooves; Saw Blades; Stikka Kannon.`,
  models: models(`Hunta Rig|10"|10|3+|6+|16|7+|5|`),
  weapons: weapons(
    `'Eavy Lobba [BLAST 2, INDIRECT FIRE]|48"|3|5+|6|0|2`,
    `Stikka Kannon [ANTI-MONSTER/VEHICLE 2+]|12"|1|5+|12|-2|3`,
    `Butcha Boyz [ANTI-MONSTER/VEHICLE 4+]|Melee|4|3+|5|-1|1`,
    `Savage Horns and Hooves [EXTRA ATTACKS, LANCE]|Melee|4|4+|8|-1|3`,
    `Saw Blades [CLEAVE 1, EXTRA ATTACKS]|Melee|6|3+|10|-2|2`,
  ),
  abilities: [
    core('Deadly Demise D6'), core('Feel No Pain 5+'), core('Firing Deck 11'), armyRule('Waaagh!'),
    ability('Fully Loaded Butchery', `This unit's Butcha Boyz weapon has +2 A for each model embarked within this unit (to a maximum of +22 A).`),
    ability('Tramplasquig Charge', `When you target this unit with the Crushing Impact stratagem, that use is -1 CP.`),
    ability('Transport', `This model has a transport capacity of 22 ${kwb('BEAST SNAGGAS INFANTRY')} models.`),
  ],
  keywords: ['Monster', 'Beast Snagga', 'Transport', 'Wagon'],
  unitComposition: ['1 Hunta Rig'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'butcha boyz', count: 1 }, { name: "'eavy lobba", count: 1 }, { name: 'savage horns and hooves', count: 1 }, { name: 'saw blades', count: 1 }, { name: 'stikka kannon', count: 1 }],
  damagedW: 6,
}),

datasheet({
  name: 'Kill Rig', role: 'Other Datasheets',
  loadout: `<b>This model is equipped with:</b> Butcha Boyz; 'Eavy Lobba; Savage Horns and Hooves; Saw Blades; Stikka Kannon; Wurrtower.`,
  models: models(`Kill Rig|10"|10|3+|6+|16|7+|5|`),
  weapons: weapons(
    `'Eavy Lobba [BLAST 2, INDIRECT FIRE]|48"|3|5+|6|0|2`,
    `Stikka Kannon [ANTI-MONSTER/VEHICLE 2+]|12"|1|5+|12|-2|3`,
    `Wurrtower [HAZARDOUS, PSYCHIC, TORRENT]|24"|1|-|12|-3|6`,
    `Butcha Boyz [ANTI-MONSTER/VEHICLE 4+, EXTRA ATTACKS]|Melee|4|3+|5|-1|1`,
    `Savage Horns and Hooves [EXTRA ATTACKS, LANCE]|Melee|4|4+|8|-1|3`,
    `Saw Blades [CLEAVE 1, EXTRA ATTACKS]|Melee|6|3+|10|-2|2`,
  ),
  abilities: [
    core('Deadly Demise D6'), core('Feel No Pain 5+'), armyRule('Unstable Energies'), armyRule('Waaagh!'),
    ability('Wurrboy', `(Psyker level 1): This model has the following psychic abilities.<br><br><b>Beastscent</b> (psychic level 1): In your Movement phase, when a unit embarked within this unit is selected to make a disembark move, if this unit is not battle-shocked, you can make a psychic roll for this unit by rolling one D6. If you do, on a 1 this unit is battle-shocked; otherwise, that disembarking unit's attacks that target a ${kwb('MONSTER')} or ${kwb('VEHICLE')} unit have +1 to wound rolls until the end of the turn.<br><br><b>Warpath</b> (psychic level 1): In the Fight phase, when this unit is selected to fight, if this unit is not battle-shocked, you can make a psychic roll for this unit by rolling one D6. If you do, on a 1 this unit is battle-shocked; otherwise this unit's melee attacks have ${kwb('[LETHAL HITS]')} and ${kwb('[PSYCHIC]')}.`),
    ability('Transport', `This model has a transport capacity of 12 ${kwb('BEAST SNAGGAS INFANTRY')} models.`),
  ],
  keywords: ['Monster', 'Beast Snagga', 'Psyker', 'Transport', 'Wagon'],
  unitComposition: ['1 Kill Rig'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'butcha boyz', count: 1 }, { name: "'eavy lobba", count: 1 }, { name: 'savage horns and hooves', count: 1 }, { name: 'saw blades', count: 1 }, { name: 'stikka kannon', count: 1 }, { name: 'wurrtower', count: 1 }],
  damagedW: 6,
}),

datasheet({
  name: 'Killa Kans', role: 'Other Datasheets',
  loadout: `<b>Every model is equipped with:</b> Kan Blasta; Kan Klaw.`,
  models: models(`Killa Kan|8"|7|3+|6+|5|8+|2|`),
  weapons: weapons(
    `Kan Blasta - Dakka [BLAST 1, IGNORES COVER, SUSTAINED HITS 1]|24"|4|4+|6|-1|1`,
    `Kan Blasta - Kill Shot|24"|2|4+|10|-2|3`,
    `Kan Blasta - Point Blank [BLAST 2, TORRENT]|12"|3|-|5|-1|1`,
    `Kan Klaw|Melee|3|4+|8|-2|3`,
  ),
  abilities: [
    core('Deadly Demise 1'), armyRule('Waaagh!'),
    ability('Spiteful Power Trip', `This unit's attacks that target a unit that has no models with a Toughness characteristic of 7+ have +1 to hit rolls.`),
  ],
  keywords: ['Vehicle', 'Grots', 'Walker'],
  unitComposition: ['3-6 Killa Kans'], modelCountMin: 3, modelCountMax: 6,
  defaultWeaponNames: [{ name: 'kan blasta', count: 1 }, { name: 'kan klaw', count: 1 }],
}),

datasheet({
  name: 'Deff Dread', role: 'Other Datasheets',
  loadout: `<b>This model is equipped with:</b> Big Shoota; Dread Klaws; Skorcha.`,
  models: models(`Deff Dread|8"|9|2+|6+|8|7+|3|`),
  weapons: weapons(
    `Big Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|36"|3|5+|5|0|1`,
    `Kustom Mega-blasta [HAZARDOUS]|24"|3|5+|9|-2|3`,
    `Rokkit Launcha - Blasta [BLAST 2]|24"|2|5+|4|0|1`,
    `Rokkit Launcha - Busta|24"|2|5+|10|-2|3`,
    `Skorcha [BLAST 1, TORRENT]|12"|3|-|5|0|1`,
    `Extra Klaw [EXTRA ATTACKS]|Melee|1|3+|12|-2|3`,
    `Dread Klaws [CLEAVE 1]|Melee|5|3+|12|-2|3`,
  ),
  options: [
    { button: '•', description: "This model's Big Shoota can be replaced with 1 Extra Klaw, 1 Kustom Mega-blasta or 1 Rokkit Launcha." },
    { button: '•', description: "This model's Skorcha can be replaced with 1 Extra Klaw, 1 Big Shoota, 1 Kustom Mega-blasta or 1 Rokkit Launcha." },
  ],
  abilities: [
    core('Deadly Demise 1'), armyRule('Waaagh!'),
    ability("Dread 'Ard", `Attacks that target this unit have -1 D.`, { effects: { damageMod: -1 }, target: 'defender' }),
  ],
  keywords: ['Vehicle', 'Walker'],
  unitComposition: ['1 Deff Dread'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'big shoota', count: 1 }, { name: 'dread klaws', count: 1 }, { name: 'skorcha', count: 1 }],
}),

datasheet({
  name: 'Gorkanaut', role: 'Other Datasheets',
  loadout: `<b>This model is equipped with:</b> Deffstorm Mega-shoota; 2 Dual Big Shoota; Klaw of Gork; 2 Rokkit Launcha; Skorcha.`,
  models: models(`Gorkanaut|9"|12|2+|6+|20|7+|8|`),
  weapons: weapons(
    `Deffstorm Mega-shoota - Aimed [LETHAL HITS: non-MONSTER/VEHICLE]|36"|20|5+|6|-1|1`,
    `Deffstorm Mega-shoota - Point Blank [TORRENT]|12"|3D6|-|6|-1|1`,
    `Dual Big Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 4]|36"|6|5+|5|0|1`,
    `Rokkit Launcha - Blasta [BLAST 2]|24"|2|5+|5|0|1`,
    `Rokkit Launcha - Busta|24"|2|5+|10|-2|3`,
    `Skorcha [BLAST 1, TORRENT]|12"|3|-|5|0|1`,
    `Klaw of Gork [CLEAVE 3]|Melee|6|3+|18|-3|6`,
  ),
  abilities: [
    core('Deadly Demise D6'), superHeavyWalker(), armyRule('Waaagh!'),
    ability('Gut Hatch', `In your Movement phase, when this unit ends a normal move, units embarked within this unit can make an assault disembark move.`),
    ability("Big an' Stompy", `This unit's melee attacks can re-roll hit rolls of 1.`, { effects: { rerollHitsOf1: true }, combatType: 'melee' }),
    ability('Transport', `This model has a transport capacity of 12 ${kwb('ORKS INFANTRY')} models. It cannot transport ${kwb('GHAZGHKULL THRAKA')} models. Each ${kwb('MEGA ARMOUR')} or ${kwb('JUMP PACK')} model takes up the space of 2 models.`),
  ],
  keywords: ['Vehicle', 'Titanic', 'Towering', 'Transport', 'Walker'],
  unitComposition: ['1 Gorkanaut'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'deffstorm mega-shoota', count: 1 }, { name: 'dual big shoota', count: 2 }, { name: 'klaw of gork', count: 1 }, { name: 'rokkit launcha', count: 2 }, { name: 'skorcha', count: 1 }],
  damagedW: 7,
}),

datasheet({
  name: 'Morkanaut', role: 'Other Datasheets',
  loadout: `<b>This model is equipped with:</b> 2 Dual Big Shoota; Klaw of Mork; Kustom Mega-blasta; Kustom Mega-zappa; 2 Rokkit Launcha.`,
  models: models(`Morkanaut|9"|12|2+|5+|20|7+|8|`),
  weapons: weapons(
    `Dual Big Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 4]|36"|6|4+|5|0|1`,
    `Kustom Mega-blasta [HAZARDOUS]|24"|3|4+|9|-2|3`,
    `Kustom Mega-zappa [BLAST 1, HAZARDOUS]|36"|3|4+|12|-2|4`,
    `Rokkit Launcha - Blasta [BLAST 2]|24"|2|4+|5|0|1`,
    `Rokkit Launcha - Busta|24"|2|4+|10|-2|3`,
    `Klaw of Mork [CLEAVE 2]|Melee|5|3+|18|-3|6`,
  ),
  abilities: [
    core('Deadly Demise D6'), superHeavyWalker(), armyRule('Waaagh!'),
    ability('Gut Hatch', `In your Movement phase, when this unit ends a normal move, units embarked within this unit can make an assault disembark move.`),
    ability("Big an' Shooty", `In your Shooting phase, this unit's ranged attacks can re-roll hit rolls of 1.`, { effects: { rerollHitsOf1: true }, combatType: 'ranged' }),
    ability('Transport', `This model has a transport capacity of 12 ${kwb('ORKS INFANTRY')} models. It cannot transport ${kwb('GHAZGHKULL THRAKA')} models. Each ${kwb('MEGA ARMOUR')} or ${kwb('JUMP PACK')} model takes up the space of 2 models.`),
  ],
  keywords: ['Vehicle', 'Titanic', 'Towering', 'Transport', 'Walker'],
  unitComposition: ['1 Morkanaut'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'dual big shoota', count: 2 }, { name: 'klaw of mork', count: 1 }, { name: 'kustom mega-blasta', count: 1 }, { name: 'kustom mega-zappa', count: 1 }, { name: 'rokkit launcha', count: 2 }],
  damagedW: 7,
}),

datasheet({
  name: 'Stompa', role: 'Other Datasheets',
  loadout: `<b>This model is equipped with:</b> 5 Big Shoota; Deffkannon and Supa-rokkits; Mega-choppa; Skorcha; Supa-gatler.`,
  models: models(`Stompa|10"|14|2+|5+|30|6+|12|`),
  weapons: weapons(
    `Big Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|36"|3|5+|5|0|1`,
    `Deffkannon and Supa-rokkits [BLAST 2]|72"|12|5+|14|-3|D6+2`,
    `Skorcha [BLAST 2, TORRENT]|12"|3|-|5|-1|1`,
    `Supa-gatler - Aimed [LETHAL HITS: non-MONSTER/VEHICLE, SUSTAINED HITS 1]|24"|30|5+|7|-2|2`,
    `Supa-gatler - Point Blank [TORRENT]|12"|3D6+3|-|7|-2|2`,
    `Mega-choppa [CLEAVE 4]|Melee|6|3+|24|-4|10`,
  ),
  abilities: [
    core('Deadly Demise 2D6'), superHeavyWalker(), armyRule('Waaagh!'),
    ability('Idol of Belligerence', `In your Movement phase, when a unit embarked within this unit is selected to make a disembark move, that unit is riled up until the start of your next turn.`),
    ability('Waaagh! Effigy', `This unit is riled up.`),
    ability('Transport', `This model has a transport capacity of 22 ${kwb('ORKS INFANTRY')} models. Each ${kwb('MEGA ARMOUR')} or ${kwb('JUMP PACK')} model takes up the space of 2 models. Each ${kwb('GHAZGHKULL THRAKA')} model takes up the space of 4 models.`),
  ],
  keywords: ['Vehicle', 'Frame', 'Titanic', 'Towering', 'Transport', 'Walker'],
  unitComposition: ['1 Stompa'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'big shoota', count: 5 }, { name: 'deffkannon and supa-rokkits', count: 1 }, { name: 'mega-choppa', count: 1 }, { name: 'skorcha', count: 1 }, { name: 'supa-gatler', count: 1 }],
  damagedW: 10,
}),

datasheet({
  name: "Big'ed Bossbunka", role: 'Other Datasheets',
  loadout: `<b>This model is equipped with:</b> Big Shoota; Gaze of Gork.`,
  models: models(`Big'ed Bossbunka|-|10|3+||12|7+|0|`),
  weapons: weapons(
    `Big Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|36"|3|5+|5|0|1`,
    `Gaze of Gork - Glare [BLAST 1]|24"|3|5+|5|0|1`,
    `Gaze of Gork - Squint|18"|1|5+|12|-3|3`,
  ),
  options: [{ button: '•', description: 'This model can be equipped with up to 3 Big Shoota.' }],
  abilities: [
    core('Deadly Demise D3'), core('Firing Deck 11'), armyRule('Waaagh!'),
    ability('Raucous Occupants', `While this model is within range of your home objective, add the OC characteristic of models embarked within this model to this model's OC characteristic.`),
    ability('Fortification', `While an enemy unit is engaged with only ${kwb('FORTIFICATION')} units: that enemy unit can be selected as a target of ranged attacks; when shooting that enemy unit, those ranged attacks have -1 to hit rolls (excluding ${kwb('[CLOSE-QUARTERS]')} attacks); when that enemy unit is selected to make a fall-back move, if it is only engaged with ${kwb('FORTIFICATION')} units and is not battle-shocked, hazard rolls made for it are automatically passed.`),
    ability('Ramshackle Cover', `When an attack targets a unit that is not fully visible to the attacking model because of this unit, the target has the benefit of cover against that attack.`),
    ability('Transport', `This model has a transport capacity of 11 ${kwb('ORKS INFANTRY')} models. It cannot transport ${kwb('GHAZGHKULL THRAKA')} models. Each ${kwb('MEGA ARMOUR')} or ${kwb('JUMP PACK')} model takes up the space of 2 models.`),
  ],
  keywords: ['Vehicle', 'Fortification', 'Frame', 'Transport'],
  unitComposition: ["1 Big'ed Bossbunka"], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'big shoota', count: 1 }, { name: 'gaze of gork', count: 1 }],
}),

datasheet({
  name: 'Blitza-bommer', role: 'Other Datasheets',
  loadout: `<b>This model is equipped with:</b> Armoured Impact; Big Shoota; Dual Supa-shoota.`,
  models: models(`Blitza-bommer|-|9|3+|6+|12|7+|0|`),
  weapons: weapons(
    `Big Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 2]|36"|3|5+|5|0|1`,
    `Dual Supa-shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 4]|36"|8|5+|6|-1|1`,
    `Armoured Impact|Melee|3|4+|6|0|1`,
  ),
  abilities: [
    core('Deadly Demise D3'), armyRule('Waaagh!'),
    ability('Boom Bomb', `At the end of your opponent's Fight phase, select one visible enemy unit (excluding Lone Operative units) within 24" of this unit and roll one D6 for that unit: on a 1-3, that unit suffers D3 mortal wounds; on a 4-5, that unit suffers 3 mortal wounds; on a 6, that unit suffers D3+3 mortal wounds.`),
  ],
  keywords: ['Vehicle', 'Aircraft', 'Fly', 'Speed Freeks'],
  unitComposition: ['1 Blitza-bommer'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'armoured impact', count: 1 }, { name: 'big shoota', count: 1 }, { name: 'dual supa-shoota', count: 1 }],
  damagedW: 4,
}),

datasheet({
  name: 'Dakkajet', role: 'Other Datasheets',
  loadout: `<b>This model is equipped with:</b> Armoured Impact; 2 Dual Supa-shoota.`,
  models: models(`Dakkajet|-|9|3+|6+|12|7+|0|`),
  weapons: weapons(
    `Dual Supa-shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 4]|36"|8|5+|6|-1|1`,
    `Armoured Impact|Melee|3|4+|6|0|1`,
  ),
  options: [{ button: '•', description: 'This model can be equipped with 1 additional Dual Supa-shoota.' }],
  abilities: [
    core('Deadly Demise D3'), armyRule('Waaagh!'),
    ability('Strafing Run', `In your Shooting phase, this unit's ranged attacks that target a unit (excluding ${kwb('FLY')} units) have +1 to hit rolls.`, { effects: { hitMod: 1 }, combatType: 'ranged' }),
  ],
  keywords: ['Vehicle', 'Aircraft', 'Fly', 'Speed Freeks'],
  unitComposition: ['1 Dakkajet'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'armoured impact', count: 1 }, { name: 'dual supa-shoota', count: 2 }],
  damagedW: 4,
}),

datasheet({
  name: 'Burna-bommer', role: 'Other Datasheets',
  loadout: `<b>This model is equipped with:</b> Armoured Impact; Dual Big Shoota; Dual Supa Shoota.`,
  models: models(`Burna-bommer|-|9|3+|6+|12|7+|0|`),
  weapons: weapons(
    `Dual Big Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 4]|36"|6|5+|5|0|1`,
    `Dual Supa Shoota [LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 4, SUSTAINED HITS 1]|36"|8|5+|6|-1|1`,
    `Skorcha Missile Rack [BLAST 2, IGNORES COVER]|36"|6|5+|5|0|1`,
    `Armoured Impact|Melee|3|4+|6|0|1`,
  ),
  options: [{ button: '•', description: 'This model can be equipped with 1 Skorcha Missile Rack.' }],
  abilities: [
    core('Deadly Demise D3'), armyRule('Waaagh!'),
    ability('Burna Bomb', `At the end of your opponent's Fight phase, select one visible enemy unit (excluding Lone Operative, ${kwb('MONSTER')} and ${kwb('VEHICLE')} units) within 36" of this unit and roll one D6 for that unit: on a 2+, that unit suffers D3 mortal wounds, cannot be hidden until the end of your next turn, and ranged attacks that target it have ${kwb('[IGNORES COVER]')} until the end of your next turn.`),
  ],
  keywords: ['Vehicle', 'Aircraft', 'Fly', 'Speed Freeks'],
  unitComposition: ['1 Burna-bommer'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'armoured impact', count: 1 }, { name: 'dual big shoota', count: 1 }, { name: 'dual supa shoota', count: 1 }],
  damagedW: 4,
}),

datasheet({
  name: 'Wazbom Blastajet', role: 'Other Datasheets',
  loadout: `<b>This model is equipped with:</b> Armoured Impact; Smasha Gun; Dual Wazbom Mega-kannon.`,
  models: models(`Wazbom Blastajet|-|9|3+|6+|12|7+|0|`),
  weapons: weapons(
    `Dual Supa-shoota [IGNORES COVER, LETHAL HITS: non-MONSTER/VEHICLE, RAPID FIRE 4]|36"|8|4+|6|-1|1`,
    `Dual Tellyport Mega-blasta [BLAST 1, IGNORES COVER, RAPID FIRE 6]|24"|6|4+|9|-2|3`,
    `Dual Wazbom Mega-kannon [HAZARDOUS, IGNORES COVER]|36"|4|4+|12|-2|4`,
    `Smasha Gun [IGNORES COVER]|48"|4|4+|6|-3|3`,
    `Armoured Impact|Melee|3|4+|6|0|1`,
  ),
  options: [
    { button: '•', description: "This model's Dual Wazbom Mega-kannon can be replaced with 1 Dual Tellyport Mega-blasta." },
    { button: '•', description: '(Wargear ability) This model can be equipped with 1 Blastajet Force Field.' },
    { button: '•', description: 'This model can be equipped with 1 Dual Supa-shoota.' },
  ],
  abilities: [
    core('Deadly Demise D3'), armyRule('Waaagh!'),
    ability('Go fer da Weak Spot', `In your Shooting phase, this unit's ranged attacks that target a ${kwb('MONSTER')} or ${kwb('VEHICLE')} unit have +1 to wound rolls.`, { effects: { woundMod: 1 }, combatType: 'ranged', requiresTargetKeyword: 'MONSTER' }),
    ability('Blastajet Force Field', `(Wargear ability): Models in this unit have a 5+ invulnerable save and do not have the ${kwb('SMOKE')} keyword.`, { effects: { saveMod: 1 }, target: 'defender' }),
  ],
  keywords: ['Vehicle', 'Aircraft', 'Fly', 'Smoke', 'Speed Freeks'],
  unitComposition: ['1 Wazbom Blastajet'], modelCountMin: 1, modelCountMax: 1,
  defaultWeaponNames: [{ name: 'armoured impact', count: 1 }, { name: 'smasha gun', count: 1 }, { name: 'dual wazbom mega-kannon', count: 1 }],
  damagedW: 4,
}),

]
